spring:
  application:
    name: ItemsBdo
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  ## SERVLET CONFIG
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 128MB
      max-request-size: 128MB

  ## DATABASE CONFIG
  datasource:
    url: jdbc:mysql://localhost:3308/bdo
    password: root
    username: root
  jpa:
    show_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      # update; create-drop; create
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: true
        jdbc:
          batch_size: 4
          order_inserts: true
        dialect: org.hibernate.dialect.MySQL5Dialect
        temp:
          use_jdbc_metadata_defaults: false
server:
  port: 8080
  servlet:
    context-path: /api